name: Build & FTP Deploy

# trigger on pushes to main (or whichever branch you choose)
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm ci

      - name: Build static site
        run: npm run build

      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server:    ${{ secrets.FTP_HOST }}
          username:  ${{ secrets.FTP_USERNAME }}
          password:  ${{ secrets.FTP_PASSWORD }}
          protocol:  ftps              # explicit TLS on control channel
          port:      21                # or your FTPS port
          local-dir: ./build/            # your SvelteKit output

